# Generated by Django 3.2.19 on 2023-07-01 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_bookingreview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreview',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
