# Generated by Django 3.2.19 on 2023-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_bookingreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreview',
            name='comment',
            field=models.TextField(max_length=100),
        ),
    ]
