# Generated by Django 3.2.19 on 2023-05-11 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(default='example@example.com', max_length=254, verbose_name='Email')),
                ('number_of_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Number of People')),
                ('date', models.DateField(verbose_name='Date')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Special Requirements')),
            ],
        ),
    ]
