# Generated by Django 3.2.19 on 2023-05-12 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='phone_number',
            field=models.IntegerField(default='07', validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)], verbose_name='Phone Number'),
        ),
    ]
