# Generated by Django 3.2.19 on 2023-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
    ]
