# Generated by Django 3.2.19 on 2023-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingform',
            name='name',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='email',
            field=models.EmailField(default='coderscave@email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='fname',
            field=models.CharField(default='First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='lname',
            field=models.CharField(default='Last name', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='special_requirements',
            field=models.TextField(default='Have any special requirements? Let us know!'),
        ),
    ]
