# Generated by Django 3.2.19 on 2023-05-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20230511_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingform',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='bookingform',
            old_name='lname',
            new_name='last_name',
        ),
    ]
