# Generated by Django 3.2.19 on 2023-05-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingform_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='phone_number',
            field=models.CharField(default='07', max_length=11, verbose_name='Phone Number'),
        ),
    ]
