# Generated by Django 3.2.19 on 2023-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingform_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
