# Generated by Django 3.2.19 on 2023-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20230511_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='number_of_people',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
    ]
