# Generated by Django 3.2.19 on 2023-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingform_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
