# Generated by Django 3.2.19 on 2023-06-01 11:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='date',
            field=models.DateField(blank=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 6, 1))]),
        ),
    ]
