# Generated by Django 3.2.19 on 2023-05-11 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20230511_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
