# Generated by Django 3.2.19 on 2023-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookingform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
    ]
