# Generated by Django 3.2.19 on 2023-06-12 11:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookingform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='date',
            field=models.DateField(blank=True, help_text='Please select a day from today onwards', validators=[django.core.validators.MinValueValidator(datetime.date(2023, 6, 12)), django.core.validators.MaxValueValidator(datetime.date(2023, 7, 12))]),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name'),
        ),
    ]
