# Generated by Django 3.2.19 on 2023-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingform_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
