# Generated by Django 3.2.19 on 2023-05-17 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingform_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='number_of_people',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Number of People'),
        ),
    ]
