# Generated by Django 3.2.19 on 2023-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20230511_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
