# Generated by Django 3.2.19 on 2023-06-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_bookingform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
